export type Category = 'restaurant' | 'activite' | 'cadeau' | 'sport' | 'cinema'

export interface Offer {
  id: string
  title: string
  description: string
  category: Category
  categoryLabel: string
  emoji: string
  gradient: string
  rating: number
  distance: string
  badge?: string
  price?: string
  address?: string
  details?: string[]
  coords?: [number, number]   // [lat, lng]
}

export const offers: Offer[] = [
  // ── RESTAURANTS ──────────────────────────────────────────
  {
    id: 'kfc-villiers',
    title: 'KFC Villiers-sur-Marne',
    description: '1 burger Colonel acheté + 1 offert',
    category: 'restaurant',
    categoryLabel: 'Restaurant',
    emoji: 'KFC',
    gradient: 'from-red-700 to-orange-500',
    rating: 4,
    distance: '0.3 km',
    badge: 'Gratuit',
    address: '12 Av. du Général de Gaulle, 94350 Villiers-sur-Marne',
    coords: [48.8284, 2.5423],
    details: [
      '1 burger Colonel acheté + 1 burger Colonel offert',
      'Valable du lundi au vendredi, hors jours fériés',
      "Non cumulable avec d'autres offres",
      "Sur présentation du bon Insolit",
    ],
  },
  {
    id: 'pizza-palace',
    title: 'Pizza Palace',
    description: "Pizza XL au prix d'une Medium",
    category: 'restaurant',
    categoryLabel: 'Restaurant',
    emoji: '🍕',
    gradient: 'from-orange-500 to-yellow-400',
    rating: 4,
    distance: '0.6 km',
    badge: '-40%',
    address: '5 Rue de la Paix, 75001 Paris',
    coords: [48.8694, 2.3314],
    details: [
      "Pizza XL au prix d'une Medium",
      'Sur toute la carte hors promotions',
      'Valable 7j/7',
      "Sur présentation du bon Insolit",
    ],
  },
  {
    id: 'pho-saigon',
    title: 'Phở Saïgon',
    description: 'Menu complet à -30%',
    category: 'restaurant',
    categoryLabel: 'Restaurant',
    emoji: '🍜',
    gradient: 'from-blue-700 to-blue-400',
    rating: 5,
    distance: '1.1 km',
    address: '22 Rue du Temple, 75004 Paris',
    coords: [48.8575, 2.3523],
    details: [
      '-30% sur le menu entrée + plat + dessert',
      'Valable du mardi au dimanche',
      'Hors boissons alcoolisées',
    ],
  },
  {
    id: 'sushi-corner',
    title: 'Sushi Corner',
    description: 'Plateau 32 pièces à 15€',
    category: 'restaurant',
    categoryLabel: 'Restaurant',
    emoji: '🍣',
    gradient: 'from-teal-500 to-blue-600',
    rating: 4,
    distance: '1.4 km',
    badge: '-50%',
    address: '8 Bd Haussmann, 75009 Paris',
    coords: [48.8740, 2.3389],
    details: [
      'Plateau 32 pièces mixtes à 15€ au lieu de 30€',
      'Valable le midi uniquement',
      'Sur réservation ou sur place',
    ],
  },
  {
    id: 'burger-king-marne',
    title: 'Burger King La Marne',
    description: 'Menu King au prix du menu Simple',
    category: 'restaurant',
    categoryLabel: 'Restaurant',
    emoji: '🍔',
    gradient: 'from-yellow-500 to-red-500',
    rating: 4,
    distance: '1.8 km',
    badge: '-20%',
    address: '3 Centre Commercial, 94100 Saint-Maur-des-Fossés',
    coords: [48.7987, 2.4986],
    details: [
      'Menu King Deluxe au prix du menu Classic',
      'Boisson + dessert inclus',
      'Valable du lundi au vendredi',
    ],
  },
  {
    id: 'le-petit-bistrot',
    title: 'Le Petit Bistrot',
    description: 'Plat du jour + café offert',
    category: 'restaurant',
    categoryLabel: 'Restaurant',
    emoji: '🥘',
    gradient: 'from-amber-600 to-orange-400',
    rating: 5,
    distance: '0.9 km',
    address: '14 Rue Mouffetard, 75005 Paris',
    coords: [48.8423, 2.3503],
    details: [
      'Plat du jour + café ou dessert offert',
      'Carte changeant chaque semaine',
      'Réservation recommandée le week-end',
    ],
  },

  // ── ACTIVITÉS ─────────────────────────────────────────────
  {
    id: 'escape-game',
    title: 'Escape Game Paris',
    description: "1h d'Escape Game à 2 pour 20€",
    category: 'activite',
    categoryLabel: 'Activité',
    emoji: '🎯',
    gradient: 'from-purple-600 to-pink-500',
    rating: 5,
    distance: '2.1 km',
    address: '18 Rue du Faubourg Saint-Antoine, 75011 Paris',
    coords: [48.8531, 2.3731],
    details: [
      "1h d'Escape Game à 2 personnes pour 20€",
      '10 scénarios au choix',
      'Sur réservation uniquement',
      'Valable tous les jours de 10h à 22h',
    ],
  },
  {
    id: 'bowling-show',
    title: 'Bowling Show',
    description: '1h de bowling + location chaussures incluse',
    category: 'activite',
    categoryLabel: 'Activité',
    emoji: '🎳',
    gradient: 'from-yellow-400 to-orange-500',
    rating: 3,
    distance: '3.2 km',
    address: '45 Av. de Clichy, 75017 Paris',
    coords: [48.8862, 2.3195],
    details: [
      '1h de bowling pour 2 personnes',
      'Location de chaussures incluse',
      'Valable en semaine avant 18h',
    ],
  },
  {
    id: 'laser-game',
    title: 'Laser Game Évasion',
    description: '2 parties de Laser Game pour le prix d\'1',
    category: 'activite',
    categoryLabel: 'Activité',
    emoji: '🔫',
    gradient: 'from-cyan-500 to-blue-600',
    rating: 4,
    distance: '1.6 km',
    badge: '-50%',
    address: '77 Rue de Rivoli, 75001 Paris',
    coords: [48.8600, 2.3422],
    details: [
      '2 parties de Laser Game pour le prix d\'1',
      'Équipement fourni',
      'Pour groupes de 4 personnes minimum',
      'Sur réservation',
    ],
  },
  {
    id: 'paintball',
    title: 'Paintball Xtreme',
    description: '100 billes offertes pour toute session',
    category: 'activite',
    categoryLabel: 'Activité',
    emoji: '🎪',
    gradient: 'from-green-600 to-teal-500',
    rating: 4,
    distance: '5.4 km',
    badge: 'Bonus',
    address: '2 Allée des Sports, 93100 Montreuil',
    coords: [48.8639, 2.4403],
    details: [
      '100 billes offertes en plus par joueur',
      'Équipement complet fourni',
      'Minimum 6 joueurs',
      'Réservation 48h à l\'avance',
    ],
  },
  {
    id: 'accrobranche',
    title: 'Forest Adventure',
    description: 'Accrobranche : enfant gratuit pour 1 adulte payant',
    category: 'activite',
    categoryLabel: 'Activité',
    emoji: '🌲',
    gradient: 'from-green-500 to-emerald-700',
    rating: 5,
    distance: '8.2 km',
    badge: '1 offert',
    address: 'Forêt de Vincennes, 75012 Paris',
    coords: [48.8374, 2.4288],
    details: [
      '1 enfant gratuit pour 1 adulte payant',
      'Parcours adapté à tous niveaux',
      'Casques et équipements fournis',
      'Ouvert le week-end et vacances scolaires',
    ],
  },
  {
    id: 'karting',
    title: 'Speed Karting',
    description: '10 minutes de karting offertes',
    category: 'activite',
    categoryLabel: 'Activité',
    emoji: '🏎️',
    gradient: 'from-red-500 to-yellow-400',
    rating: 4,
    distance: '12 km',
    badge: 'Bonus',
    address: '25 Rue de l\'Industrie, 93200 Saint-Denis',
    coords: [48.9362, 2.3557],
    details: [
      '10 min offertes pour toute session de 20 min',
      'Obligatoire : avoir 16 ans ou plus',
      'Combinaisons et casques fournis',
    ],
  },
  {
    id: 'stand-up',
    title: 'Le Comedy Club',
    description: '1 place achetée = 1 place offerte',
    category: 'activite',
    categoryLabel: 'Activité',
    emoji: '🎤',
    gradient: 'from-violet-600 to-purple-400',
    rating: 5,
    distance: '3.7 km',
    badge: '2 pour 1',
    address: '42 Rue des Martyrs, 75009 Paris',
    coords: [48.8809, 2.3397],
    details: [
      '1 place achetée = 1 place offerte',
      'Valable sur tous les spectacles hors premium',
      'Sur réservation en ligne avec code INSOLIT',
    ],
  },
  {
    id: 'yoga',
    title: 'Yoga Studio Zen',
    description: '3 séances découverte à 15€',
    category: 'activite',
    categoryLabel: 'Activité',
    emoji: '🧘',
    gradient: 'from-pink-400 to-purple-500',
    rating: 5,
    distance: '0.7 km',
    badge: 'Promo',
    address: '9 Rue de la Roquette, 75011 Paris',
    coords: [48.8531, 2.3713],
    details: [
      '3 séances de yoga au choix pour 15€',
      'Hatha, Vinyasa ou Yin yoga',
      'Tapis et accessoires fournis',
      'Valable pour nouveaux membres uniquement',
    ],
  },

  // ── CADEAUX ───────────────────────────────────────────────
  {
    id: 'box-surprise',
    title: 'Box Surprise Insolit',
    description: 'Box cadeau mystère à 9.99€',
    category: 'cadeau',
    categoryLabel: 'Cadeau',
    emoji: '🎁',
    gradient: 'from-pink-500 to-orange-400',
    rating: 5,
    distance: '—',
    badge: 'Exclusif',
    details: [
      'Box mystère avec 5 cadeaux surprises',
      'Valeur garantie minimum 30€',
      'Livraison offerte en France métropolitaine',
      'Personnalisable selon tes centres d\'intérêt',
    ],
  },
  {
    id: 'bon-achat',
    title: 'Bon d\'achat Premium',
    description: '50€ d\'achat pour 25€',
    category: 'cadeau',
    categoryLabel: 'Cadeau',
    emoji: '💎',
    gradient: 'from-purple-600 to-blue-400',
    rating: 4,
    distance: '—',
    badge: '-50%',
    details: [
      '50€ d\'achat chez nos partenaires pour 25€',
      'Valable dans + de 200 enseignes',
      'Utilisable en 1 ou plusieurs fois',
      'Validité 12 mois',
    ],
  },
  {
    id: 'coffret-bienetre',
    title: 'Coffret Bien-être',
    description: 'Spa & massage 1h offert',
    category: 'cadeau',
    categoryLabel: 'Cadeau',
    emoji: '🌟',
    gradient: 'from-teal-400 to-yellow-300',
    rating: 5,
    distance: '—',
    badge: 'Offert',
    details: [
      '1h de massage suédois ou californien',
      'Accès au spa inclus (piscine, sauna, hammam)',
      'Valable dans 15 spas partenaires en France',
      'Sur réservation, sous 6 mois',
    ],
  },
  {
    id: 'gaming-night',
    title: 'Gaming Night VIP',
    description: 'Soirée jeux vidéo privatisée',
    category: 'cadeau',
    categoryLabel: 'Cadeau',
    emoji: '🎮',
    gradient: 'from-indigo-600 to-purple-500',
    rating: 4,
    distance: '—',
    badge: 'VIP',
    details: [
      '3h de gaming en salle privée pour 4 personnes',
      'Accès aux dernières consoles (PS5, Xbox, VR)',
      'Boissons et snacks inclus',
      'Réservation 72h à l\'avance',
    ],
  },
  {
    id: 'livre-personnalise',
    title: 'Livre Photo Personnalisé',
    description: 'Album photo 40 pages à -60%',
    category: 'cadeau',
    categoryLabel: 'Cadeau',
    emoji: '📚',
    gradient: 'from-amber-400 to-rose-400',
    rating: 4,
    distance: '—',
    badge: '-60%',
    details: [
      'Album photo 20x20cm, 40 pages',
      'Couverture rigide personnalisée',
      '-60% sur le tarif standard',
      'Livraison en 5 à 7 jours ouvrés',
    ],
  },
  {
    id: 'cours-cuisine',
    title: 'Atelier Cuisine Chef',
    description: 'Cours de cuisine gastronomique à 2',
    category: 'cadeau',
    categoryLabel: 'Cadeau',
    emoji: '👨‍🍳',
    gradient: 'from-orange-400 to-red-400',
    rating: 5,
    distance: '—',
    badge: 'Promo',
    address: '30 Rue du Bac, 75007 Paris',
    coords: [48.8566, 2.3274],
    details: [
      '2h de cours de cuisine avec un chef étoilé',
      'Repas dégusté à la fin de l\'atelier',
      'Pour 2 personnes',
      'Sur réservation avec code INSOLIT',
    ],
  },

  // ── SPORT ────────────────────────────────────────────────
  {
    id: 'basic-fit',
    title: 'Basic Fit Fitness',
    description: 'Séance découverte gratuite',
    category: 'sport',
    categoryLabel: 'Sport',
    emoji: '🏋️',
    gradient: 'from-green-500 to-purple-600',
    rating: 4,
    distance: '0.5 km',
    badge: 'Gratuit',
    address: '55 Av. d\'Italie, 75013 Paris',
    coords: [48.8275, 2.3564],
    details: [
      '1 séance découverte gratuite sans engagement',
      'Accès à toutes les machines',
      'Cours collectifs inclus',
      'Valable pour les nouveaux membres uniquement',
    ],
  },
  {
    id: 'padel',
    title: 'Padel Club Paris',
    description: '1h de padel à 2 pour 10€',
    category: 'sport',
    categoryLabel: 'Sport',
    emoji: '🎾',
    gradient: 'from-yellow-400 to-green-500',
    rating: 4,
    distance: '2.3 km',
    badge: '-50%',
    address: '18 Rue du Stade, 75019 Paris',
    coords: [48.8789, 2.3986],
    details: [
      '1h de terrain de padel pour 2 joueurs à 10€',
      'Raquettes disponibles à la location',
      'Valable en semaine avant 17h',
    ],
  },
  {
    id: 'piscine',
    title: 'Aquacentre Marne',
    description: 'Entrée piscine + accès aquagym',
    category: 'sport',
    categoryLabel: 'Sport',
    emoji: '🏊',
    gradient: 'from-blue-400 to-cyan-400',
    rating: 3,
    distance: '1.2 km',
    badge: '-30%',
    address: '2 Rue du Lac, 94000 Créteil',
    coords: [48.7898, 2.4596],
    details: [
      'Entrée piscine Olympic + cours d\'aquagym',
      '-30% sur le tarif plein',
      'Casier et serviette inclus',
      'Valable le week-end uniquement',
    ],
  },

  // ── CINÉMA ───────────────────────────────────────────────
  {
    id: 'cinema-gaumont',
    title: 'Cinéma Gaumont',
    description: 'Place de cinéma à 5€',
    category: 'cinema',
    categoryLabel: 'Cinéma',
    emoji: '🎬',
    gradient: 'from-pink-600 to-purple-600',
    rating: 4,
    distance: '0.8 km',
    badge: '-50%',
    address: '74 Av. des Champs-Élysées, 75008 Paris',
    coords: [48.8706, 2.3071],
    details: [
      'Place de cinéma à 5€ toutes séances',
      'Valable en semaine avant 17h',
      'Hors avant-premières et films 3D',
    ],
  },
  {
    id: 'mk2',
    title: 'MK2 Quai de Seine',
    description: 'Soirée ciné : 2 places + 2 boissons',
    category: 'cinema',
    categoryLabel: 'Cinéma',
    emoji: '🍿',
    gradient: 'from-red-500 to-pink-400',
    rating: 5,
    distance: '3.1 km',
    badge: 'Pack',
    address: '14 Quai de la Seine, 75019 Paris',
    coords: [48.8842, 2.3697],
    details: [
      '2 places de cinéma + 2 boissons au choix',
      'Valable tous les jours',
      'Hors avant-premières et événements spéciaux',
    ],
  },
]

export const testimonials = [
  {
    id: 1,
    name: 'Sophie L.',
    role: 'Étudiante, Paris',
    avatar: 'SL',
    gradient: 'from-pink-500 to-orange-400',
    rating: 5,
    text: '"Insolit a changé ma façon de sortir. Je découvre des endroits incroyables à des prix imbattables !"',
  },
  {
    id: 2,
    name: 'Thomas M.',
    role: 'Développeur, Lyon',
    avatar: 'TM',
    gradient: 'from-purple-600 to-blue-400',
    rating: 5,
    text: "\"J'utilise Insolit chaque semaine. Les offres restaurants sont juste top, ça m'économise un max !\"",
  },
  {
    id: 3,
    name: 'Amina B.',
    role: 'Designer, Marseille',
    avatar: 'AB',
    gradient: 'from-teal-400 to-yellow-300',
    rating: 4,
    text: '"Super pratique, l\'interface est intuitive et les offres sont vraiment intéressantes. Je recommande !"',
  },
]

export const steps = [
  { number: 1, emoji: '📲', title: 'Trouve ton offre',        desc: "Parcours les centaines d'offres disponibles près de chez toi par catégorie ou sur la carte." },
  { number: 2, emoji: '🔍', title: 'Sélectionne un bon plan', desc: "Choisis l'offre qui te correspond parmi restaurants, activités, cadeaux et bien plus." },
  { number: 3, emoji: '✅', title: 'Réclame ton offre',       desc: "Active ton bon plan directement depuis l'app et présente-le au partenaire en quelques secondes." },
  { number: 4, emoji: '🎉', title: 'Profite et partage',      desc: "Vis l'expérience, partage ton avis et accumule des badges pour débloquer encore plus d'avantages." },
]

export const features = [
  {
    icon: '🎯',
    gradient: 'from-pink-500 to-orange-400',
    title: 'Des réductions et certains prix adulte',
    desc: "Profite de tarifs préférentiels dans des centaines d'enseignes partenaires près de chez toi.",
  },
  {
    icon: '⚡',
    gradient: 'from-orange-500 to-yellow-400',
    title: 'Des activités Insolites faire maintenant',
    desc: "Réserve des expériences uniques et mémorables disponibles immédiatement autour de toi.",
  },
  {
    icon: '🎁',
    gradient: 'from-purple-600 to-pink-500',
    title: 'Des cadeaux et offres exclusives',
    desc: "Découvre des cadeaux personnalisés et des offres exclusives réservées aux membres Insolit.",
  },
  {
    icon: '🗺️',
    gradient: 'from-teal-400 to-blue-400',
    title: 'Explore et découvre autour de toi',
    desc: "Visualise toutes les offres sur une carte interactive et repère les bons plans du quartier.",
  },
]
